version: '3.8'

services:
  poll_ftp:
    image: ftp-download-poller:latest
    container_name: poll_ftp
    environment:
      - FTP_SERVER=ftp.example.com
      - FTP_USERNAME=username
      - FTP_PASSWORD=password
      - FTP_DIR=/remote/directory
    volumes:
      - /your/local/download/path:/download
    build:
      context: .
      dockerfile: Dockerfile
